using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace ColletteAPI.Models.Domain
{
    public class User
    {
        [BsonId]  // Marks this field as the MongoDB ID field
        [BsonRepresentation(BsonType.ObjectId)]  // Ensures MongoDB can convert between ObjectId and string
        public string Id { get; set; }  // This will store the ObjectId generated by MongoDB

        [BsonElement("NIC")]
        public string NIC { get; set; }

        [BsonElement("Email")]
        public string Email { get; set; }

        [BsonElement("FirstName")]
        public string FirstName { get; set; }

        [BsonElement("LastName")]
        public string LastName { get; set; }

        [BsonElement("Username")]
        public string Username { get; set; }

        [BsonElement("PasswordHash")]
        public string PasswordHash { get; set; }

        [BsonElement("UserType")]
        public string UserType { get; set; }

        [BsonElement("IsActive")]
        public bool IsActive { get; set; }
        [BsonElement("ContactNumber")]
        public string ContactNumber { get; set; }
        [BsonElement("Address")]
        public string Address { get; set; }
    }
}
