/*
 * File: User.cs
 * Description: This file defines the `User` class, which represents a user in the system. The class is mapped to a MongoDB collection and includes various user attributes such as NIC, email, and user roles.
 */
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace ColletteAPI.Models.Domain
{
    /*
     * Class: User
     * Represents a user in the system. Contains information such as user ID, name, contact details, and roles. 
     * This class is mapped to a MongoDB document, with each property being stored as a field in MongoDB.
     */
    public class User
    {
        [BsonId]  // Marks this field as the MongoDB ID field (primary key).
        [BsonRepresentation(BsonType.ObjectId)]  // Ensures that MongoDB can convert between ObjectId and string automatically.
        public string Id { get; set; }  // This will store the ObjectId generated by MongoDB

        [BsonElement("NIC")]
        public string NIC { get; set; }

        [BsonElement("Email")]
        public string Email { get; set; }

        [BsonElement("FirstName")]
        public string FirstName { get; set; }

        [BsonElement("LastName")]
        public string LastName { get; set; }

        [BsonElement("Username")]
        public string Username { get; set; }

        [BsonElement("PasswordHash")]
        public string PasswordHash { get; set; }

        [BsonElement("UserType")]
        public string UserType { get; set; }

        [BsonElement("IsActive")]
        public bool IsActive { get; set; }
        [BsonElement("ContactNumber")]
        public string ContactNumber { get; set; }
        [BsonElement("Address")]
        public string Address { get; set; }
    }
}
